name: Node.js Deploy

on:
  push:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Application
        run: npm run build
        
      - name: Install sshpass
        run: sudo apt-get install -y sshpass
      
      - name: Deploy via SFTP
        env:
          SSHPASS: ${{ secrets.SFTP_PASSWORD }}
        run: |
          # Stellt sicher, dass Verbindungsfehler nicht ignoriert werden
          set -e
          
          # Kopiert den Build-Ordner mit sshpass und scp
          sshpass -e scp -o StrictHostKeyChecking=no -P ${{ secrets.SFTP_PORT }} -r ./dist/* ${{ secrets.SFTP_USERNAME }}@${{ secrets.SFTP_SERVER }}:${{ secrets.SFTP_REMOTE_PATH }}
          
          echo "::notice::Node.js app was successfully deployed to ${{ secrets.SFTP_SERVER }}:${{ secrets.SFTP_REMOTE_PATH }}"
